const defaultBanner = 'Welcome to Wictory Wonderful House!'

// generated by the following code:
//
// require('gradient-string')([
//     { color: '#42d392', pos: 0 },
//     { color: '#42d392', pos: 0.1 },
//     { color: '#647eff', pos: 1 }
//   ])('Welcome to Wictory Wonderful House!')
//
// Use the output directly here to keep the bundle small.
const gradientBanner = '\u001b[38;2;66;211;146mW\u001b[39m\u001b[38;2;66;211;146me\u001b[39m\u001b[38;2;66;211;146ml\u001b[39m\u001b[38;2;66;211;146mc\u001b[39m\u001b[38;2;67;208;150mo\u001b[39m\u001b[38;2;69;205;154mm\u001b[39m\u001b[38;2;70;202;158me\u001b[39m \u001b[38;2;71;198;162mt\u001b[39m\u001b[38;2;72;195;166mo\u001b[39m \u001b[38;2;74;192;170mW\u001b[39m\u001b[38;2;75;189;174mi\u001b[39m\u001b[38;2;76;186;178mc\u001b[39m\u001b[38;2;77;183;182mt\u001b[39m\u001b[38;2;79;180;186mo\u001b[39m\u001b[38;2;80;176;190mr\u001b[39m\u001b[38;2;81;173;194my\u001b[39m \u001b[38;2;82;170;198mW\u001b[39m\u001b[38;2;84;167;203mo\u001b[39m\u001b[38;2;85;164;207mn\u001b[39m\u001b[38;2;86;161;211md\u001b[39m\u001b[38;2;87;157;215me\u001b[39m\u001b[38;2;89;154;219mr\u001b[39m\u001b[38;2;90;151;223mf\u001b[39m\u001b[38;2;91;148;227mu\u001b[39m\u001b[38;2;92;145;231ml\u001b[39m \u001b[38;2;94;142;235mH\u001b[39m\u001b[38;2;95;139;239mo\u001b[39m\u001b[38;2;96;135;243mu\u001b[39m\u001b[38;2;97;132;247ms\u001b[39m\u001b[38;2;99;129;251me\u001b[39m\u001b[38;2;100;126;255m!\u001b[39m'

export { defaultBanner, gradientBanner }